feat(just): Add sourceable tooling for just and refine reorg (#194)
* feat(just): add initial sourcable just library with UI tooling for just recipes

* feat(just): add some basic coloring functionality

* chore(just): add warning about required double quoting of colors for bg

* chore(just): add mention of cpick in how you can grab the colors for bash

* feat(just): add more colors

* chore(just): move away from tput

* feat(just): add vars to remove formatting

* chore(just): change Ui_choice to Choose

* feat(just): add confirm function

* chore(just): change script name to libjust.sh

* chore(just): cleanup and move recipes over to use new library

* chore(just): disable 2 shellshecks for formatting

* feat(just): add distrobox function

* chore(just): update documentation comment for Distrobox

* feat(just): add support for all distrobox args and do some cleanup

* fix(just): add libfunctions.sh to build.sh

* fix(just): fix wrong path for libjust in spec file

* chore(just): correctly copy libjust files

* chore(just): remove unused var

* chore(just): up the version in spec file

* chore(just): comply with SC1091 as the files might not exist on the system yet

* chore(just): update header to use libformatting

* chore(just): simplify attribute change for libjust

* feat(just): add devbox-global equivalent to setup-devbox

* chore(just): disable relevant shellchecks for global variables

* chore(just): reverse fzf layout and make shellcheck compliant

* chore(just): add ${n} as alias for ${normal}

* chore(just): make comment about basic colors more clear

* feat(just): add support for distrobox assemble

* feat(just): add distrobox-new and distrobox-assemble

* feat(just): add tui option for assemble ALL containers

* fix(just): use correct image for systems without mutter

* feat(distrobox): add mlbox and change ubuntu to github container

* feat(just): add AssembleList

* chore(just): remove mlbox

* chore(just): add header and remove bazzite-arch

* chore(just): update libjust path to /usr/lib/ujust/libjust.sh

* chore(just): cleanup distrobox-new command

* chore(just): disable dry-run for Assemble

* chore(just): remove fedora-docker container

* chore: move distrobox.ini to usr/etc/distrobox/

* chore: revert just distrobox refactor

* chore:  update documentation

* chore(just): move ujust libraries to separate folder

* chore(just): move distrobox specific functions to #197

* fix(just): correct the spec file now that the entryfile is named ujust.sh

* fix(just): adjust spec file to correctly add shell libraries to /usr/bin/ujust/

* chore(just): change spec file to use %{_exec_prefix}/lib/ujust instead of hardcoded path

---------

Co-authored-by: Benjamin Sherman <benjamin@holyarmy.org>

diff --git a/build/ublue-os-just/ugum b/build/ublue-os-just/ugum
--- a/build/ublue-os-just/ugum
+++ b/build/ublue-os-just/ugum
@@ -15,12 +15,12 @@ GUM=$(which gum 2>/dev/null)
 # Check if fzf is installed and set it as the handler
 FALLBACK_HANDLER=$(which fzf 2>/dev/null)
 HANDLER=""
-if [[ ! -z $FALLBACK_HANDLER ]]; then
+if [[ -n $FALLBACK_HANDLER ]]; then
     HANDLER="fzf"
 fi
 
 # If $MENU is set
-if [[ ! -z $MENU ]]; then
+if [[ -n $MENU ]]; then
     for BIN in "${SUPPORTED_HANDLERS[@]}"
     do
         if [[ "$BIN" == "$MENU" ]]; then
@@ -29,10 +29,16 @@ if [[ ! -z $MENU ]]; then
     done
 fi
 
+# Logic for what to do if gum is not installed
 function noGum () {
     if [[ -z "$1" ]]; then
         # If no arguments are provided then error with 
         echo "ugum supports only choose or confirm as the first argument!"
+        echo "Usage:"
+        echo '    ugum choose option1 option2 \"option 3\"'
+        echo '        Returns: selected string'
+        echo '    ugum confirm "this is an optional question'
+        echo '        Returns: exit code in $? will be 0 for YES and 1 for NO'
         exit 5
     elif [[ "$1" == "choose" ]]; then
         # If choose is the verb then run the choose function and pass all remaining args to an appropriate handler
@@ -55,6 +61,7 @@ function noGum () {
     fi
 }
 
+# Implements a generic bash choice dialog
 function choose_Generic () {
     # Change PS3 to our select prompt
     PS3='Please enter your choice: '
@@ -87,6 +94,7 @@ function choose_Generic () {
     done 
 }
 
+# Implements a choice dialog using fzf
 function choose_Fzf () {
     # Change our select prompt
     PROMPT='Please select your choice: '
@@ -108,9 +116,10 @@ function choose_Fzf () {
     done
 
     # Make a select prompt using fzf
-    echo -e $OPTIONS | fzf --height="~20%" --prompt="$PROMPT"
+    echo -e "$OPTIONS" | fzf --layout=reverse --height="~20%" --prompt="$PROMPT"
 }
 
+# Implements a generic bash confirm dialog
 function confirm_Generic () {
     # Set default prompt
     PROMPT="Are you sure?"
@@ -128,14 +137,16 @@ function confirm_Generic () {
     confirm_Parse "$YESNO"
 }
 
+# Implements a confirm dialog in fzf
 function confirm_Fzf () {
     PROMPT=$(confirm_getPrompt "$@")
 
     # Make the confirm prompt using fzf and read response
-    YESNO=$(echo -e "Yes\nNo" | fzf --height="~20%" --prompt="$PROMPT ")
+    YESNO=$(echo -e "Yes\nNo" | fzf --layout=reverse --height="~20%" --prompt="$PROMPT ")
     confirm_Parse "$YESNO"
 }
 
+# Gets the prompt for the confirm dialog, with a fallback to "Are you sure?"
 function confirm_getPrompt () {
     # Set default prompt
     PROMPT="Are you sure?"
@@ -149,9 +160,10 @@ function confirm_getPrompt () {
     done
 
     # Return the prompt
-    echo $PROMPT
+    echo "$PROMPT"
 }
 
+# Parse the confirm response and translate it the same exit codes gum uses
 function confirm_Parse () {
     case "$@" in
         [Yy]*)
